[package]
name = "bfss"
description = "Use Brainfuck to make a server"
version = "0.1.0"
authors = ["interrrp <int@addictedto.coffee>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
